### ISSUE TITLE
how to set different port for different node?

### ISSUE THREAD

**Issue by zqhxuyuan** [open-web3-stack/parachain-launch#1]
My test node already took 9944, so the alice will fail.

```
Successfully built ade9e97efc96
Successfully tagged output_parachain-2000-2:latest
Creating output_relaychain-alice_1 ...
Creating output_relaychain-alice_1   ... error
Creating output_parachain-2000-2_1   ...
Creating output_relaychain-bob_1     ...
Creating output_parachain-2000-0_1   ...
Creating output_relaychain-charlie_1 ... done
Creating output_parachain-2000-2_1   ... done
Creating output_relaychain-bob_1     ... done
Creating output_parachain-2000-0_1   ... done
Creating output_parachain-2000-1_1   ... done

ERROR: for relaychain-alice  Cannot start service relaychain-alice: driver failed programming external connectivity on endpoint output_relaychain-alice_1 (676ada3124c18e8788fca06873bd7a8c1c534736f6a0d07e39babdb26d49963f): Error starting userland proxy: listen tcp4 0.0.0.0:9944: bind: address already in use
```

**Comment by zjb0807** [comment]
Modify `output/docker-compose.yml`. 
e.g.
```
version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
```

9944:9944 -> 19944:9944
