### ISSUE TITLE
Support for env variables in image name

### ISSUE THREAD

**Issue by 5tan-enj** [open-web3-stack/parachain-launch#104]
Currently facing the following issue:

This is the `config.yaml` file

```yaml
# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.28
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
  nodes:
    - name: alice
      wsPort: 9944
      rpcPort: 9933
      port: 30333
      flags:
        - --force-authoring
      env:
        RUST_LOG: babe=debug
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
- image: ${DOCKER_IMAGE_PATH}:${DOCKER_IMAGE_TAG}  ## <-- The env for image ##
  chain:
    base: rocfinity-local
  id: 2021
  parachain: true
  flags:
    - --force-authoring
    - --rpc-methods=unsafe
    - --execution=wasm
  relaychainFlags:
    - --execution=wasm
    - --port=30343
    - --rpc-methods=Auto
  env:
    RUST_LOG: runtime=debug,sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug,pallet-collator-staking=trace,xcm=trace,pallet-xcm=trace
  volumePath: /data
  nodes:
  - wsPort: 10010
    rpcPort: 10011
    port: 40334
    flags:
      - --alice
  - wsPort: 10012
    rpcPort: 10013
    port: 40335
    flags:
      - --bob
```

When running `./node_modules/@open-web3/parachain-launch/bin/parachain-launch generate -y configs/config.yaml`, it produces the following file

```
FROM ${DOCKER_IMAGE_PATH}:${DOCKER_IMAGE_TAG}
COPY . /app
```

and this results in an error since the ARGS are not added to the dockerfile from [here](https://github.com/open-web3-stack/parachain-launch/blob/3ce2819ca2896c3b074e58bfddbf172b967e51b0/src/index.ts#L411)

Is it possible to do this any other way?
