### ISSUE TITLE
[feat] Use Polkadot UI

### ISSUE THREAD

**Issue by TAnas0** [open-web3-stack/parachain-launch#119]
As suggested in the official Polkadot node documentation, one can set up a Grafana Dashboard for the node(s).
I was able to quickly set it up by adding the following into `docker-compose.yaml`:

```yaml
services:
  # Polkadot UI: https://github.com/paritytech/polkadot/blob/master/doc/docker.md#using-docker-compose
  polkadotui:
    container_name: polkadotui
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://127.0.0.1:9944
    ports:
      - 8080:80
```

Is there a way to make this an option into this tool? Would it be nice to have?
If so, can we get some pointers from the contributors on how to implement it?
